using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PanelFadeIn : MonoBehaviour
{
    CanvasGroup canvasGroup;
    [SerializeField] float FadeInSpeed;
    private void Awake()
    {
        canvasGroup = GetComponent<CanvasGroup>();
        canvasGroup.alpha = 0;
    }
    private void OnEnable()
    {
        StartCoroutine(FadeInCorroutine());
    }
    IEnumerator FadeInCorroutine()
    {
        canvasGroup.alpha = 0;
        while (canvasGroup.alpha < 0.9)
        {
            canvasGroup.alpha = Mathf.Lerp(canvasGroup.alpha, 1f, FadeInSpeed);
            yield return null;
        }
        canvasGroup.alpha = 1;
        yield return null;
    }
}
